name: 'Deploy to Environment Notification'
description: 'Notifies SonOfYellr about a new deployment'
author: 'IdeaCrew, Inc.'
inputs:
  payload_url: # change this
    required: true
    description: 'where the payload should be sent'
    default: 'default value if applicable'
runs:
  using: 'node12'
  main: 'dist/index.js'
